const shopItems = [
  // ======================== GENERAL EQUIPMENT ========================

  // -- Drugs & Poisons --
  {
    id: "rabbit",
    name: "Rabbit",
    price: 150,
    category: "drugs",
    consumable: true,
    legality: "Illegal",
    type: "Drug",
    description:
      "Fast-acting, neurostimulant known for its intense, notably addictive, aphrodisiacal properties. Banned in several counties but sold regularly underground.",
  },
  {
    id: "mummy",
    name: "Mummy",
    price: 400,
    category: "drugs",
    consumable: true,
    legality: "Illegal",
    type: "Drug",
    description:
      "Powerful, fast-acting analgesic patch-drug. Numbs pain and slows metabolism for several hours.",
  },
  {
    id: "euphoria",
    name: "Euphoria",
    price: 250,
    category: "drugs",
    consumable: true,
    legality: "Illegal",
    type: "Drug",
    description:
      "Substrate compound drawn from synthetic psilocybin-D3. Causes vivid visual, auditory, tactile, and cognitive hallucinations of bliss, pleasure, and relaxation that lasts several hours. Somewhat addictive.",
  },
  {
    id: "bloodmist",
    name: "Bloodmist",
    price: 800,
    category: "drugs",
    consumable: true,
    legality: "Condemned",
    type: "Drug",
    description:
      "Aerosolized combat drug administered through direct inhalation. Triggers a temporary, dissociative rage that enhances pain tolerance and strength for a short period of time before leaving the user exhausted and prone to seizure or mental collapse.",
  },
  {
    id: "tranquilizer",
    name: "Tranquilizer",
    price: 300,
    category: "drugs",
    consumable: true,
    legality: "Illegal",
    type: "Poison",
    emulated: "Drow Poison",
    description:
      "Rapid response sedative administered via injury or injection meant to immobilize targets.",
  },

  // -- Medical --
  {
    id: "nanite-contraception-pill",
    name: "Nanite Contraception Pill",
    price: 200,
    category: "medical",
    consumable: true,
    legality: "Open",
    type: "Medication",
    description:
      "Also known as a ‘nanny pill.’ Single-dose nanite capsule either ingested or inserted into cervical cavity (the former is suggested). Specifically targets the endometrium to terminate or prevent fertilization. Prevents 99.99% of pregnancies from occurring within a week",
  },
  {
    id: "stim",
    name: "Stim",
    price: 200,
    category: "medical",
    consumable: true,
    legality: "Open",
    type: "Medication",
    emulated: "Potion of Healing",
    description:
      "Injected drug to immediately help repair the body of minor injuries.",
  },
  {
    id: "stim2",
    name: "Stim+",
    price: 500,
    category: "medical",
    consumable: true,
    legality: "Open",
    type: "Medication",
    emulated: "Potion of Greater Healing",
    description:
      "Injected drug to immediately help repair the body of moderate injuries.",
  },
  {
    id: "stim3",
    name: "Stim++",
    price: 1000,
    category: "medical",
    consumable: true,
    legality: "Open",
    type: "Medication",
    emulated: "Potion of Superior Healing",
    description:
      "Injected drug to immediately help repair the body of dangerous injuries.",
  },
  {
    id: "stim4",
    name: "Stim+++",
    price: 2000,
    category: "medical",
    consumable: true,
    legality: "Open",
    type: "Medication",
    emulated: "Potion of Supreme Healing",
    description:
      "Simple autoinjector outfitted with pain killers, modified clot compounds, and synthetic stem cells to rapidly control and repair significant bodily injuries.",
  },

  // -- Technology --
  {
    id: "netsuit-advanced",
    name: "Netsuit (advanced)",
    price: 1000000,
    category: "technology",
    consumable: false,
    legality: "Restricted",
    type: "Technology",
    emulated: "Cloak of the Archmage",
    description:
      "Full-body neuromesh suit specially designed for netrunning and immersive deep-diving. A dedicated, miniature supercomputer array encased in a spinal module allows the port user to compute at 10 bits a second.",
  },
  {
    id: "cube-shield",
    name: "Cube Shield",
    price: 400000,
    category: "technology",
    consumable: false,
    legality: "Illegal",
    type: "Technology",
    emulated: "Cube of Force",
    description:
      "Fist-sized energy-field generator capable of producing a large shielded area in the shape of a cube or rectangular prism.",
  },
  {
    id: "retinal-scanner",
    name: "Retinal Scanner",
    price: 200000,
    category: "technology",
    consumable: false,
    legality: "Illegal",
    type: "Technology",
    description:
      "Biometric scanning device that can be used to log or record retinal data and reproduce it via a specialized mimic lens. Reads retinal patterns up to 2cm.",
  },
  {
    id: "prototype-biosuit",
    name: "Prototype Biosuit",
    price: 180000,
    category: "technology",
    consumable: false,
    legality: "Illegal",
    type: "Technology",
    emulated: "Barbarian Rage",
    description:
      "Experimental haptic suit outfitted with intuitive nanite weaves for protection and haptic response. Absurdly flexible, breathable, and form-fitting, it integrates directly via user port to grant highly supplemented strength, endurance, and agility.",
  },
  {
    id: "auto-bento",
    name: "Auto-bento",
    price: 7000,
    category: "technology",
    consumable: false,
    legality: "Open",
    type: "Technology",
    description:
      "Self-heating meal unit which stores and prepares lunches automatically.",
  },
  {
    id: "door-jammer",
    name: "Door Jammer",
    price: 300,
    category: "technology",
    consumable: false,
    legality: "Restricted",
    type: "Technology",
    emulated: "Arcane Lock spell",
    description:
      "Quickhack module that can be placed onto a standard electronic door frame to cause it to lock. Surprisingly diverse in the amount of doors it can affect.",
  },
  {
    id: "bit-sticker",
    name: "Bit Sticker",
    price: 100,
    category: "technology",
    consumable: true,
    legality: "Prohibited",
    type: "Technology",
    emulated: "Spell Scroll (systemized)",
    description:
      "Single-use netrunning quickhack patch. Pre-loaded with one systemised program, which it executes onto whatever it is attached to.",
  },

  // -- Equipment & Gear --
  {
    id: "dogupal",
    name: "Dogupal",
    price: 3500,
    category: "equipment",
    consumable: false,
    legality: "Open",
    type: "Equipment",
    emulated: "All-purpose tool",
    description:
      "Modular multi-tool. Adapts to most mechanical and electronic tasks provided it is equipped with specific modules designed for said tasks. Modules sold separately.",
  },
  {
    id: "reinforced-clothing",
    name: "Reinforced Clothing",
    price: 65000,
    category: "gear",
    consumable: false,
    legality: "Open",
    type: "Clothing",
    emulated: "Cloak of Protection",
    description:
      "Street-grade clothing with woven impact-resistant fibres. Fashionable and functional.",
  },
  {
    id: "adaptive-binoculars",
    name: "Adaptive Binoculars",
    price: 1000,
    category: "equipment",
    consumable: false,
    legality: "Open",
    type: "Equipment",
    description: "Auto-focus optics with digital zoom and low-light assist.",
  },
  {
    id: "double-dragon",
    name: "Double Dragon",
    price: 400,
    category: "equipment",
    consumable: false,
    legality: "Open",
    type: "Sex Toy",
    description: "High-end dual-motor pleasure device. Discretely packaged.",
  },
  {
    id: "rations-1-weeks-worth",
    name: "Rations (1 week's worth)",
    price: 100,
    category: "equipment",
    consumable: true,
    legality: "Open",
    type: "Equipment",
    description: "Compressed nutrient blocks. Tasteless but sufficient.",
  },
  {
    id: "smokes-20",
    name: "Smokes (20)",
    price: 10,
    category: "equipment",
    consumable: true,
    legality: "Open",
    type: "Equipment",
    description:
      "Pack of 20 filtered cigarettes. A blonde slut comes around here asking for them every week.",
  },

  // -- Cyberware (General) --
  {
    id: "training-chip-feat",
    name: "Training Chip (feat)",
    price: 250000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    description:
      "Neural imprint of a physical feat. Installs muscle memory directly.",
  },
  {
    id: "training-chip-skill",
    name: "Training Chip (skill)",
    price: 100000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    description:
      "Skill-pattern chip. Uploads proficiency in one chosen discipline.",
  },
  {
    id: "training-chip-language",
    name: "Training Chip (language)",
    price: 25000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    description:
      "Language acquisition chip. Fluency installed in under an hour.",
  },

  // -- Robotics --
  {
    id: "spiderbot-advanced",
    name: "Spiderbot (advanced)",
    price: 80000,
    category: "robotics",
    consumable: false,
    legality: "Restricted",
    type: "Robotics",
    emulated: "Enhanced Imp familiar",
    description:
      "Autonomous eight-legged drone with enhanced sensory and combat packages. Can walk up and down walls and use cloaking.",
  },
  {
    id: "emergent-crawler",
    name: "Emergent Crawler",
    price: 75000,
    category: "robotics",
    consumable: false,
    legality: "Regulated",
    type: "Robotics",
    description:
      "Emergency response robot which can sling onto patients up to 400 pounds and administer CPR procedures during transport.",
  },
  {
    id: "spiderbot-simple",
    name: "Spiderbot (simple)",
    price: 2000,
    category: "robotics",
    consumable: false,
    legality: "Regulated",
    type: "Robotics",
    emulated: "Imp familiar",
    description:
      "Basic remote-operated spider unit. Surveillance and light utility.",
  },
  {
    id: "drone-simple",
    name: "Drone (simple)",
    price: 1000,
    category: "robotics",
    consumable: false,
    legality: "Open",
    type: "Robotics",
    emulated: "Find Familiar scroll",
    description:
      "Entry-level aerial drone. Remote-piloted with standard camera feed.",
  },
  {
    id: "robodachi",
    name: "Robodachi",
    price: 20000,
    category: "robotics",
    consumable: false,
    legality: "Open",
    type: "Robotics",
    description:
      "Dedicated companion robot meant to assist in various academic and ecological tasks. Had a worse name before.",
  },

  // -- Optics (Lens Upgrades) --
  {
    id: "x-ray-lenses",
    name: "X-ray Lenses",
    price: 10000,
    category: "optics",
    consumable: false,
    legality: "Prohibited",
    type: "Lens Upgrade",
    emulated: "Ring of X-ray Vision",
    description:
      "Lens overlay that penetrates up to 30cm of non-lead material.",
  },
  {
    id: "anti-cloak-lenses",
    name: "Anti-cloak Lenses",
    price: 6000,
    category: "optics",
    consumable: false,
    legality: "Regulated",
    type: "Lens Upgrade",
    emulated: "See Invisibility spell",
    description:
      "Detects active stealth fields and optical camouflage systems.",
  },
  {
    id: "thermal-lenses",
    name: "Thermal Lenses",
    price: 4000,
    category: "optics",
    consumable: false,
    legality: "Regulated",
    type: "Lens Upgrade",
    description: "Overlays heat signatures onto normal vision in real time.",
  },

  // -- Weapons --
  {
    id: "integrated-silencer-pistol",
    name: "Integrated Silencer Pistol",
    price: 2000,
    category: "weapons",
    consumable: false,
    legality: "Restricted",
    type: "Weapon",
    emulated: "Automatic Pistol",
    description: "Compact pistol with factory-fitted integral suppressor.",
  },
  {
    id: "basic-pistol",
    name: "Basic Pistol",
    price: 500,
    category: "weapons",
    consumable: false,
    legality: "Regulated",
    type: "Weapon",
    emulated: "Automatic Pistol",
    description:
      "Standard semi-automatic sidearm. Reliable and widely available.",
  },
  {
    id: "slowball",
    name: "Slowball",
    price: 500,
    category: "weapons",
    consumable: true,
    legality: "Open",
    type: "Weapon",
    description:
      "Throwable gel-charge that releases a localised slow field on impact.",
  },

  // -- Weapon Mods --
  {
    id: "rail-rifling",
    name: "Rail Rifling",
    price: 10000,
    category: "weapon-mods",
    consumable: false,
    legality: "Regulated",
    type: "Firearm Upgrade",
    emulated: "+1 Weapon",
    description:
      "Magnetic rail lining that significantly improves projectile velocity.",
  },
  {
    id: "silencer",
    name: "Silencer",
    price: 1000,
    category: "weapon-mods",
    consumable: false,
    legality: "Restricted",
    type: "Firearm Upgrade",
    description:
      "Threaded suppressor attachment. Reduces muzzle report and flash.",
  },

  // ======================== CYBERNETICS ========================

  {
    id: "rapelling-arm",
    name: "Rapelling Arm",
    price: 300,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Arm",
    emulated: "Grappling hook",
    description:
      "Forearm-mounted grapple launcher with 30m of reinforced cable.",
  },
  {
    id: "bioregulator-f-m",
    name: "Bioregulator (♀/♂)",
    price: 500,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Womb or balls",
    description: "Lowers chance of pregnancy by altering sperm motility",
  },
  {
    id: "alcohol-regulator",
    name: "Alcohol Regulator",
    price: 750,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Liver",
    emulated: "Tankard of Sobriety",
    description:
      "Liver implant that filters alcohol before it reaches the bloodstream.",
  },
  {
    id: "magnification-opticals",
    name: "Magnification Opticals",
    price: 2000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Eyes",
    emulated: "Eyes of Minute Seeing",
    description: "Ocular implant for detail vision of up to 100x zoom.",
  },
  {
    id: "nightvision-mod",
    name: "Nightvision Mod",
    price: 2000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Eyes",
    emulated: "Goggles of Night",
    description: "Retinal overlay enabling full vision in near-total darkness.",
  },
  {
    id: "refraction-opticals",
    name: "Refraction Opticals",
    price: 2000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Eyes",
    emulated: "Eyes of the Eagle",
    description: "Sharpens long-range vision to telescopic clarity.",
  },
  {
    id: "pregnancy-detector",
    name: "Preconception Module",
    price: 2000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Womb",
    description:
      "AI program that analyzes hormonal activity and uterine wall to predict with significant accuracy the likelihood of a pregnancy mere hours after coitus.",
  },
  {
    id: "arm-launcher",
    name: "Arm Launcher",
    price: 3000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Arms",
    emulated: "Grenade launcher",
    description: "Forearm-integrated grenade launcher with auto-feed chamber.",
  },
  {
    id: "bioinhibitor-f-m",
    name: "Bioinhibitor (♀/♂)",
    price: 3000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Womb or balls",
    description: "Ensures protection from pregnancy at will",
  },
  {
    id: "prosthetic-arms",
    name: "Prosthetic Arms",
    price: 7000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Arms",
    description:
      "Full cybernetic arm replacement. Strength and dexterity enhanced.",
  },
  {
    id: "fall-suspension",
    name: "Fall Suspension",
    price: 9000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Legs",
    emulated: "Monk: Slow Fall (1/2 level)",
    description: "Leg dampeners that absorb kinetic force from extreme drops.",
  },
  {
    id: "arc-launcher",
    name: "Arc Launcher",
    price: 10000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Arms",
    emulated: "Catapult, varying levels",
    description: "Launches any held object via pneumatic piston action.",
  },
  {
    id: "monowire-base",
    name: "Monowire (base)",
    price: 10000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Arms",
    description:
      "Wrist-mounted monofilament wire. Cuts through most materials.",
  },
  {
    id: "advanced-npc",
    name: "Advanced NPC",
    price: 15000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Neural",
    emulated: "Docent",
    description:
      "A special neural interface that provides detailed bodily statistics and life support, along with assistance with miscellaneous tasks.",
  },
  {
    id: "laser-module",
    name: "Laser Module",
    price: 20000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Eyes, arms, or chest",
    emulated: "Circlet of Blasting",
    description:
      "Implanted laser emitter. Precise cutting and combat application.",
  },
  {
    id: "homeostatic-regulator",
    name: "Homeostatic Regulator",
    price: 25000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Immune",
    emulated: "Amulet of Health",
    description:
      "Full internal management module that supplements the immune system, intaking data from parts of the body and using said data to induce optimal hormonal dispersal.",
  },
  {
    id: "artificial-liver",
    name: "Artificial Liver",
    price: 25000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Liver",
    description:
      "Cybernetic liver replacement capable of filtering various poisons or generating antidotes for unregistered ones.",
    emulated: "Periapt of Proof Against Poison",
  },
  {
    id: "pseudoembryonic-cell-builder",
    name: "Pseudoembryonic Cell Builder (PEM-Cell)",
    price: 27000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Back",
    emulated: "Amulet of Health, faster installation",
    description:
      "Accelerated stem cell growth implant. Dramatically reduces recovery time.",
  },
  {
    id: "dermal-cloaking",
    name: "Dermal Cloaking",
    price: 50000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Cloak of Elvenkind",
    description:
      "Skin-layer light-bending mesh. Reduces visual and thermal signature.",
  },
  {
    id: "nano-tract-apendages",
    name: "Nano-tract Apendages",
    price: 58000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Hands, feet",
    emulated: "Slippers of Spider Climbing",
    description:
      "Nanoscale adhesive pads on hands and feet for surface climbing.",
  },
  {
    id: "bouldering-module",
    name: "Bouldering Module",
    price: 60000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Arms, legs",
    emulated: "Ring of Swimming and Climbing",
    description:
      "Limb reinforcements for scaling sheer vertical and aquatic surfaces.",
  },
  {
    id: "thermal-optics",
    name: "Thermal Optics",
    price: 100000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Eyes",
    description:
      "Full-spectrum thermal vision implant. Sees through smoke and walls.",
  },
  {
    id: "hostile-refactorizer",
    name: "Hostile Refactorizer",
    price: 200000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Neural",
    emulated: "Ring of Spell Turning (systems only)",
    description:
      "Neural buffer that intercepts and redirects hostile system intrusions.",
  },
  {
    id: "holography",
    name: "Holography",
    price: 200000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Cloak of Displacement",
    description:
      "Skin-mounted holo-emitters create a persistent displacement afterimage.",
  },
  {
    id: "asura-arms",
    name: "Asura Arms",
    price: 250000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Back, spine",
    description:
      "Provides user with an extra pair of arms planted on the back along an artificial spine",
  },
  {
    id: "sonar-view-ultrasight",
    name: "Sonar View (Ultrasight)",
    price: 250000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Eyes",
    emulated: "Ring of X-ray Vision (audio)",
    description:
      "Echolocation implant. Maps surroundings through walls via audio pulses.",
  },
  {
    id: "bullet-time",
    name: "Bullet Time",
    price: 250000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Neural",
    emulated: "Time Stop spell, 1 turn",
    description:
      "Neural overclock that briefly compresses perceived time to a crawl.",
  },
  {
    id: "stealth-epidermals",
    name: "Stealth Epidermals",
    price: 400000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Cloak of Invisibility",
    description:
      "Full-body optical camouflage skin. Near-perfect invisibility.",
  },
  {
    id: "winter-module",
    name: "Winter Module",
    price: 600000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Torso",
    emulated: "Shield of the Uven Rune",
    description:
      "Torso implant generating a reactive cold-energy barrier on impact.",
  },
  {
    id: "regeneration-factor",
    name: "Regeneration Factor",
    price: 1000000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Immune",
    emulated: "Ring of Regeneration",
    description:
      "Immune overhaul enabling accelerated tissue and organ regeneration.",
  },
  {
    id: "experimental-dermals",
    name: "Experimental Dermals",
    price: 5000000,
    category: "cyberware",
    consumable: false,
    legality: "Illegal",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Armor of Invulnerability",
    description:
      "Prototype subdermal plating. Renders the user nearly impervious to damage.",
  },

  // -- Cyberware (unpriced / negotiable) --
  {
    id: "contracting-blades",
    name: "Contracting Blades",
    price: 15000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Arms",
    emulated: "Rapier",
    description:
      "Retractable monofilament blades that extend from the forearm.",
  },
  {
    id: "transfusion-needle",
    name: "Transfusion Needle",
    price: 28000,
    category: "cyberware",
    consumable: false,
    legality: "Illegal",
    type: "Cyberware",
    bodyPart: "Arms",
    emulated: "Enervation spell",
    description:
      "Arm-mounted needle that drains biological energy from a target.",
  },
  {
    id: "integral-neurography",
    name: "Integral Neurography",
    price: 85000,
    category: "cyberware",
    consumable: false,
    legality: "Illegal",
    type: "Cyberware",
    bodyPart: "Brain",
    emulated: "Ring of Mind Shielding",
    description:
      "Brain implant that actively blocks external psionic and digital intrusion.",
  },
  {
    id: "vampiric-transfuser",
    name: "Vampiric Transfuser",
    price: 42000,
    category: "cyberware",
    consumable: false,
    legality: "Illegal",
    type: "Cyberware",
    bodyPart: "Digestive",
    emulated: "Vampiric Touch spell",
    description:
      "Digestive implant that converts absorbed blood into usable energy.",
  },
  {
    id: "exoplating",
    name: "Exoplating",
    price: 60000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Heavy armor",
    description: "Price varies by coverage and material",
  },
  {
    id: "suppression-rope",
    name: "Suppression Rope",
    price: 22000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Arm",
    emulated: "Rope of Entanglement",
    description:
      "Arm-launched entanglement wire. Immobilises targets on contact.",
  },
  {
    id: "flight-deck",
    name: "Flight Deck",
    price: 500000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Back or feet",
    emulated: "Wings of Flying",
    description:
      "Retractable thruster wings enabling sustained personal flight.",
  },
  {
    id: "rocket-feet",
    name: "Rocket Feet",
    price: 55000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Feet",
    emulated: "Winged Boots",
    description:
      "Foot-mounted jet boosters for rapid vertical and horizontal bursts.",
  },

  // ======================== AUTOMOTIVE UPGRADES ========================

  {
    id: "smoke-screen-system",
    name: "Smoke Screen System",
    price: 2500,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Releases dense smoke clouds for obscuring vision.",
  },
  {
    id: "grappling-hooks",
    name: "Grappling Hooks",
    price: 4000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Allows the car to latch onto structures or other vehicles.",
  },
  {
    id: "hydraulic-suspension",
    name: "Hydraulic Suspension",
    price: 4500,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Adjusts the car's height for improved maneuverability.",
  },
  {
    id: "turbo-boost",
    name: "Turbo Boost",
    price: 5000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Provides a burst of speed for quick acceleration and maneuvering.",
  },
  {
    id: "emp-pulse-emitter",
    name: "EMP Pulse Emitter",
    price: 6000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Emits an EMP pulse to disable nearby electronic systems.",
  },
  {
    id: "neural-jammer",
    name: "Neural Jammer",
    price: 6500,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Emits electronic interference to disrupt nearby targeting systems.",
  },
  {
    id: "holographic-projector",
    name: "Holographic Projector",
    price: 7000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Creates realistic holographic decoys to confuse enemies. (Mislead 1/day?)",
  },
  {
    id: "reinforced-chassis",
    name: "Reinforced Chassis",
    price: 8000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Strengthens the car's structure for increased durability. (Tough?)",
  },
  {
    id: "electro-magnetic-grappler",
    name: "Electro-Magnetic Grappler",
    price: 8500,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Latches onto metallic surfaces for maneuvering and scaling walls.",
  },
  {
    id: "nano-spider-tires",
    name: "Nano-Spider Tires",
    price: 9000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Adjusts tread patterns for optimized grip on different terrains.",
  },
  {
    id: "energy-shield-generator",
    name: "Energy Shield Generator",
    price: 10000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Projects a protective force field around the car.",
  },
  {
    id: "kinetic-thrusters",
    name: "Kinetic Thrusters",
    price: 10000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Enables lateral strafing and brief hovering for evasive actions.",
  },
  {
    id: "oil-slick",
    name: "Oil Slick",
    price: 10000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Releases a slick of oil from the car's rear, causing loss of control for pursuing vehicles.",
  },
  {
    id: "molecular-disruptor-mines",
    name: "Molecular Disruptor Mines",
    price: 11000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Deploys destabilizing mines to impair handling of other vehicles.",
  },
  {
    id: "auto-targeting-turret",
    name: "Auto-Targeting Turret",
    price: 12000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Mounts an auto-targeting turret for offensive capabilities.",
  },
  {
    id: "sonic-disruptor",
    name: "Sonic Disruptor",
    price: 12000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Emits powerful sound waves to disorient enemies during combat.",
  },
  {
    id: "adaptive-camouflage-paint",
    name: "Adaptive Camouflage Paint",
    price: 14000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Provides adaptive camouflage to blend with surroundings.",
  },
  {
    id: "neural-interface",
    name: "Neural Interface",
    price: 15000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Connects the car's systems directly to the driver's brain.",
  },
  {
    id: "flame-thrower",
    name: "Flame Thrower",
    price: 15000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Equips the car with a mounted flamethrower for offensive use. (Scorching Ray 2/day)",
  },
  {
    id: "energy-absorption-matrix",
    name: "Energy Absorption Matrix",
    price: 18000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Absorbs and redirects energy-based attacks for defense.",
  },
  {
    id: "cloaking-device",
    name: "Cloaking Device",
    price: 20000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Renders the car temporarily invisible. (Invisibility 1/day)",
  },
  {
    id: "rocket-launcher",
    name: "Rocket Launcher",
    price: 20000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Concealed rocket launcher with guided rockets. (Fireball 1/day)",
  },
  {
    id: "whistle",
    name: "Whistle",
    price: 8000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "An application that calls the car to your location via ping signal if transport is possible.",
  },
  {
    id: "vulcan-cannon-turret",
    name: "Vulcan Cannon Turret",
    price: 45000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Military-grade anti-automobile rifle mounted on a retractable swivel deck.",
  },

  // ======================== VEHICLES ========================

  {
    id: "scooter",
    name: "Scooter",
    price: 3000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Small",
    capacity: 1,
    description:
      "Lightweight single-seat bike. Fast and nimble in tight urban spaces.",
  },
  {
    id: "motorcycle",
    name: "Motorcycle",
    price: 25000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Small",
    capacity: 2,
    description: "Heavier two-seat bike with improved stability at high speed.",
  },
  {
    id: "three-wheeler",
    name: "Three-wheeler",
    price: 20000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Small",
    capacity: 2,
    description: "Compact tri-wheel vehicle. Stable and fuel-efficient.",
  },
  {
    id: "roadster",
    name: "Roadster",
    price: 55000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Medium",
    capacity: 2,
    description: "Open-top two-seater built for speed on open roads.",
  },
  {
    id: "coupe",
    name: "Coupe",
    price: 40000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Medium",
    capacity: 4,
    description: "Sleek four-seat performance car. Balances speed and comfort.",
  },
  {
    id: "sedan",
    name: "Sedan",
    price: 35000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Medium",
    capacity: 5,
    description: "Standard five-seat vehicle. Reliable and inconspicuous.",
  },
  {
    id: "muscle-car",
    name: "Muscle Car",
    price: 48000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Large",
    capacity: 5,
    description:
      "High-displacement V8 coupe built for straight-line power. Raw, loud, and distinctly American.",
  },
  {
    id: "sports-car",
    name: "Sports Car",
    price: 55000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Small",
    capacity: 2,
    description:
      "Lightweight two-seater built for handling and agility. Prioritises driver feel over comfort.",
  },
  {
    id: "luxury-car",
    name: "Luxury Car",
    price: 78000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Large",
    capacity: 5,
    description:
      "Premium sedan with high-end materials, advanced tech, and a refined ride.",
  },
];

// Category labels for filter buttons
const shopCategories = {
  all: "ALL ITEMS",
  drugs: "DRUGS",
  medical: "MEDICAL",
  technology: "TECH",
  equipment: "EQUIPMENT",
  gear: "GEAR",
  cyberware: "CYBERWARE",
  robotics: "ROBOTICS",
  optics: "OPTICS",
  weapons: "WEAPONS",
  "weapon-mods": "WEAPON MODS",
  automotive: "AUTOMOTIVE",
  vehicles: "VEHICLES",
};
