// ==================== SHOP INVENTORY DATA ====================
// Converted from Cyberpunk_Equipment.xlsx
// consumable: true  → can be bought multiple times (never grays out)
// consumable: false → one-time purchase, grays out after buying
// price: 0 = price unlisted / negotiable

const shopItems = [
  // ======================== GENERAL EQUIPMENT ========================

  // -- Drugs & Poisons --
  {
    id: "rabbit",
    name: "Rabbit",
    price: 150,
    category: "drugs",
    consumable: true,
    legality: "Illegal",
    type: "Drug",
  },
  {
    id: "mummy",
    name: "Mummy",
    price: 400,
    category: "drugs",
    consumable: true,
    legality: "Illegal",
    type: "Drug",
  },
  {
    id: "euphoria",
    name: "Euphoria",
    price: 250,
    category: "drugs",
    consumable: true,
    legality: "Illegal",
    type: "Drug",
  },
  {
    id: "bloodmist",
    name: "Bloodmist",
    price: 800,
    category: "drugs",
    consumable: true,
    legality: "Condemned",
    type: "Drug",
  },
  {
    id: "tranquilizer",
    name: "Tranquilizer",
    price: 300,
    category: "drugs",
    consumable: true,
    legality: "Illegal",
    type: "Poison",
    emulated: "Drow Poison",
  },

  // -- Medical --
  {
    id: "nanite-contraception-pill",
    name: "Nanite Contraception Pill",
    price: 200,
    category: "medical",
    consumable: true,
    legality: "Open",
    type: "Medication",
  },

  // -- Technology --
  {
    id: "netsuit-advanced",
    name: "Netsuit (advanced)",
    price: 1000000,
    category: "technology",
    consumable: false,
    legality: "Restricted",
    type: "Technology",
    emulated: "Cloak of the Archmage",
  },
  {
    id: "cube-shield",
    name: "Cube Shield",
    price: 400000,
    category: "technology",
    consumable: false,
    legality: "Illegal",
    type: "Technology",
    emulated: "Cube of Force",
  },
  {
    id: "retinal-scanner",
    name: "Retinal Scanner",
    price: 200000,
    category: "technology",
    consumable: false,
    legality: "Illegal",
    type: "Technology",
  },
  {
    id: "prototype-biosuit",
    name: "Prototype Biosuit",
    price: 180000,
    category: "technology",
    consumable: false,
    legality: "Illegal",
    type: "Technology",
    emulated: "Barbarian Rage",
  },
  {
    id: "auto-bento",
    name: "Auto-bento",
    price: 7000,
    category: "technology",
    consumable: false,
    legality: "Open",
    type: "Technology",
  },
  {
    id: "door-jammer",
    name: "Door Jammer",
    price: 300,
    category: "technology",
    consumable: false,
    legality: "Restricted",
    type: "Technology",
    emulated: "Arcane Lock spell",
  },
  {
    id: "bit-sticker",
    name: "Bit Sticker",
    price: 100,
    category: "technology",
    consumable: true,
    legality: "Prohibited",
    type: "Technology",
    emulated: "Spell Scroll (systemized)",
  },

  // -- Equipment & Gear --
  {
    id: "dogupal",
    name: "Dogupal",
    price: 3500,
    category: "equipment",
    consumable: false,
    legality: "Open",
    type: "Equipment",
    emulated: "All-purpose tool",
  },
  {
    id: "reinforced-clothing",
    name: "Reinforced Clothing",
    price: 65000,
    category: "gear",
    consumable: false,
    legality: "Open",
    type: "Clothing",
    emulated: "Cloak of Protection",
  },
  {
    id: "adaptive-binoculars",
    name: "Adaptive Binoculars",
    price: 1000,
    category: "equipment",
    consumable: false,
    legality: "Open",
    type: "Equipment",
  },
  {
    id: "double-dragon",
    name: "Double Dragon",
    price: 400,
    category: "equipment",
    consumable: false,
    legality: "Open",
    type: "Sex Toy",
  },
  {
    id: "rations-1-weeks-worth",
    name: "Rations (1 week's worth)",
    price: 100,
    category: "equipment",
    consumable: true,
    legality: "Open",
    type: "Equipment",
  },
  {
    id: "smokes-20",
    name: "Smokes (20)",
    price: 10,
    category: "equipment",
    consumable: true,
    legality: "Open",
    type: "Equipment",
  },

  // -- Cyberware (General) --
  {
    id: "training-chip-feat",
    name: "Training Chip (feat)",
    price: 250000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
  },
  {
    id: "training-chip-skill",
    name: "Training Chip (skill)",
    price: 100000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
  },
  {
    id: "training-chip-language",
    name: "Training Chip (language)",
    price: 25000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
  },

  // -- Robotics --
  {
    id: "spiderbot-advanced",
    name: "Spiderbot (advanced)",
    price: 80000,
    category: "robotics",
    consumable: false,
    legality: "Restricted",
    type: "Robotics",
    emulated: "Enhanced Imp familiar",
  },
  {
    id: "emergent-crawler",
    name: "Emergent Crawler",
    price: 75000,
    category: "robotics",
    consumable: false,
    legality: "Regulated",
    type: "Robotics",
  },
  {
    id: "spiderbot-simple",
    name: "Spiderbot (simple)",
    price: 2000,
    category: "robotics",
    consumable: false,
    legality: "Regulated",
    type: "Robotics",
    emulated: "Imp familiar",
  },
  {
    id: "drone-simple",
    name: "Drone (simple)",
    price: 1000,
    category: "robotics",
    consumable: false,
    legality: "Open",
    type: "Robotics",
    emulated: "Find Familiar scroll",
  },

  // -- Optics (Lens Upgrades) --
  {
    id: "x-ray-lenses",
    name: "X-ray Lenses",
    price: 10000,
    category: "optics",
    consumable: false,
    legality: "Prohibited",
    type: "Lens Upgrade",
    emulated: "Ring of X-ray Vision",
  },
  {
    id: "anti-cloak-lenses",
    name: "Anti-cloak Lenses",
    price: 6000,
    category: "optics",
    consumable: false,
    legality: "Regulated",
    type: "Lens Upgrade",
    emulated: "See Invisibility spell",
  },
  {
    id: "thermal-lenses",
    name: "Thermal Lenses",
    price: 4000,
    category: "optics",
    consumable: false,
    legality: "Regulated",
    type: "Lens Upgrade",
  },

  // -- Weapons --
  {
    id: "integrated-silencer-pistol",
    name: "Integrated Silencer Pistol",
    price: 2000,
    category: "weapons",
    consumable: false,
    legality: "Restricted",
    type: "Weapon",
    emulated: "Automatic Pistol",
  },
  {
    id: "basic-pistol",
    name: "Basic Pistol",
    price: 500,
    category: "weapons",
    consumable: false,
    legality: "Regulated",
    type: "Weapon",
    emulated: "Automatic Pistol",
  },
  {
    id: "slowball",
    name: "Slowball",
    price: 500,
    category: "weapons",
    consumable: true,
    legality: "Open",
    type: "Weapon",
  },

  // -- Weapon Mods --
  {
    id: "rail-rifling",
    name: "Rail Rifling",
    price: 10000,
    category: "weapon-mods",
    consumable: false,
    legality: "Regulated",
    type: "Firearm Upgrade",
    emulated: "+1 Weapon",
  },
  {
    id: "silencer",
    name: "Silencer",
    price: 1000,
    category: "weapon-mods",
    consumable: false,
    legality: "Restricted",
    type: "Firearm Upgrade",
  },

  // ======================== CYBERNETICS ========================

  {
    id: "rapelling-arm",
    name: "Rapelling Arm",
    price: 300,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Arm",
    emulated: "Grappling hook",
  },
  {
    id: "bioregulator-f-m",
    name: "Bioregulator (♀/♂)",
    price: 500,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Womb or balls",
    description: "Lowers chance of pregnancy by altering sperm motility",
  },
  {
    id: "alcohol-regulator",
    name: "Alcohol Regulator",
    price: 750,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Liver",
    emulated: "Tankard of Sobriety",
  },
  {
    id: "magnification-opticals",
    name: "Magnification Opticals",
    price: 2000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Eyes",
    emulated: "Eyes of Minute Seeing",
  },
  {
    id: "nightvision-mod",
    name: "Nightvision Mod",
    price: 2000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Eyes",
    emulated: "Goggles of Night",
  },
  {
    id: "refraction-opticals",
    name: "Refraction Opticals",
    price: 2000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Eyes",
    emulated: "Eyes of the Eagle",
  },
  {
    id: "pregnancy-detector",
    name: "Pregnancy Detector",
    price: 2000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Womb",
    description:
      "Informs the user via their HUD the moment they have been impregnated",
  },
  {
    id: "arm-launcher",
    name: "Arm Launcher",
    price: 3000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Arms",
    emulated: "Grenade launcher",
  },
  {
    id: "bioinhibitor-f-m",
    name: "Bioinhibitor (♀/♂)",
    price: 3000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Womb or balls",
    description: "Ensures protection from pregnancy at will",
  },
  {
    id: "prosthetic-arms",
    name: "Prosthetic Arms",
    price: 7000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Arms",
  },
  {
    id: "fall-suspension",
    name: "Fall Suspension",
    price: 9000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Legs",
    emulated: "Monk: Slow Fall (1/2 level)",
  },
  {
    id: "arc-launcher",
    name: "Arc Launcher",
    price: 10000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Arms",
    emulated: "Catapult, varying levels",
  },
  {
    id: "monowire-base",
    name: "Monowire (base)",
    price: 10000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Arms",
  },
  {
    id: "advanced-npc",
    name: "Advanced NPC",
    price: 15000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Neural",
    description:
      "A special neural interface that provides detailed bodily statistics and life support",
    emulated: "Docent",
  },
  {
    id: "laser-module",
    name: "Laser Module",
    price: 20000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Eyes, arms, or chest",
    emulated: "Circlet of Blasting",
  },
  {
    id: "homeostatic-regulator",
    name: "Homeostatic Regulator",
    price: 25000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Immune",
    emulated: "Amulet of Health",
  },
  {
    id: "artificial-liver",
    name: "Artificial Liver",
    price: 25000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Liver",
    description: "Cybernetic liver capable of processing various poisons",
    emulated: "Periapt of Proof Against Poison",
  },
  {
    id: "pseudoembryonic-cell-builder",
    name: "Pseudoembryonic Cell Builder (PEM-Cell)",
    price: 27000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Back",
    emulated: "Amulet of Health, faster installation",
  },
  {
    id: "dermal-cloaking",
    name: "Dermal Cloaking",
    price: 50000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Cloak of Elvenkind",
  },
  {
    id: "nano-tract-apendages",
    name: "Nano-tract Apendages",
    price: 58000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Hands, feet",
    emulated: "Slippers of Spider Climbing",
  },
  {
    id: "bouldering-module",
    name: "Bouldering Module",
    price: 60000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Arms, legs",
    emulated: "Ring of Swimming and Climbing",
  },
  {
    id: "thermal-optics",
    name: "Thermal Optics",
    price: 100000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Eyes",
  },
  {
    id: "hostile-refactorizer",
    name: "Hostile Refactorizer",
    price: 200000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Neural",
    emulated: "Ring of Spell Turning (systems only)",
  },
  {
    id: "holography",
    name: "Holography",
    price: 200000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Cloak of Displacement",
  },
  {
    id: "asura-arms",
    name: "Asura Arms",
    price: 250000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Back, spine",
    description:
      "Provides user with an extra pair of arms planted on the back along an artificial spine",
  },
  {
    id: "sonar-view-ultrasight",
    name: "Sonar View (Ultrasight)",
    price: 250000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Eyes",
    emulated: "Ring of X-ray Vision (audio)",
  },
  {
    id: "bullet-time",
    name: "Bullet Time",
    price: 250000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Neural",
    emulated: "Time Stop spell, 1 turn",
  },
  {
    id: "stealth-epidermals",
    name: "Stealth Epidermals",
    price: 400000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Cloak of Invisibility",
  },
  {
    id: "winter-module",
    name: "Winter Module",
    price: 600000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Torso",
    emulated: "Shield of the Uven Rune",
  },
  {
    id: "regeneration-factor",
    name: "Regeneration Factor",
    price: 1000000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Immune",
    emulated: "Ring of Regeneration",
  },
  {
    id: "experimental-dermals",
    name: "Experimental Dermals",
    price: 5000000,
    category: "cyberware",
    consumable: false,
    legality: "Illegal",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Armor of Invulnerability",
  },

  // -- Cyberware (unpriced / negotiable) --
  {
    id: "contracting-blades",
    name: "Contracting Blades",
    price: 15000,
    category: "cyberware",
    consumable: false,
    legality: "Regulated",
    type: "Cyberware",
    bodyPart: "Arms",
    emulated: "Rapier",
  },
  {
    id: "transfusion-needle",
    name: "Transfusion Needle",
    price: 28000,
    category: "cyberware",
    consumable: false,
    legality: "Illegal",
    type: "Cyberware",
    bodyPart: "Arms",
    emulated: "Enervation spell",
  },
  {
    id: "integral-neurography",
    name: "Integral Neurography",
    price: 85000,
    category: "cyberware",
    consumable: false,
    legality: "Illegal",
    type: "Cyberware",
    bodyPart: "Brain",
    emulated: "Ring of Mind Shielding",
  },
  {
    id: "vampiric-transfuser",
    name: "Vampiric Transfuser",
    price: 42000,
    category: "cyberware",
    consumable: false,
    legality: "Illegal",
    type: "Cyberware",
    bodyPart: "Digestive",
    emulated: "Vampiric Touch spell",
  },
  {
    id: "exoplating",
    name: "Exoplating",
    price: 60000,
    category: "cyberware",
    consumable: false,
    legality: "Open",
    type: "Cyberware",
    bodyPart: "Skin",
    emulated: "Heavy armor",
    description: "Price varies by coverage and material",
  },
  {
    id: "suppression-rope",
    name: "Suppression Rope",
    price: 22000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Arm",
    emulated: "Rope of Entanglement",
  },
  {
    id: "flight-deck",
    name: "Flight Deck",
    price: 500000,
    category: "cyberware",
    consumable: false,
    legality: "Prohibited",
    type: "Cyberware",
    bodyPart: "Back or feet",
    emulated: "Wings of Flying",
  },
  {
    id: "rocket-feet",
    name: "Rocket Feet",
    price: 55000,
    category: "cyberware",
    consumable: false,
    legality: "Restricted",
    type: "Cyberware",
    bodyPart: "Feet",
    emulated: "Winged Boots",
  },

  // ======================== AUTOMOTIVE UPGRADES ========================

  {
    id: "smoke-screen-system",
    name: "Smoke Screen System",
    price: 2500,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Releases dense smoke clouds for obscuring vision.",
  },
  {
    id: "grappling-hooks",
    name: "Grappling Hooks",
    price: 4000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Allows the car to latch onto structures or other vehicles.",
  },
  {
    id: "hydraulic-suspension",
    name: "Hydraulic Suspension",
    price: 4500,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Adjusts the car's height for improved maneuverability.",
  },
  {
    id: "turbo-boost",
    name: "Turbo Boost",
    price: 5000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Provides a burst of speed for quick acceleration and maneuvering.",
  },
  {
    id: "emp-pulse-emitter",
    name: "EMP Pulse Emitter",
    price: 6000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Emits an EMP pulse to disable nearby electronic systems.",
  },
  {
    id: "neural-jammer",
    name: "Neural Jammer",
    price: 6500,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Emits electronic interference to disrupt nearby targeting systems.",
  },
  {
    id: "holographic-projector",
    name: "Holographic Projector",
    price: 7000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Creates realistic holographic decoys to confuse enemies. (Mislead 1/day?)",
  },
  {
    id: "reinforced-chassis",
    name: "Reinforced Chassis",
    price: 8000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Strengthens the car's structure for increased durability. (Tough?)",
  },
  {
    id: "electro-magnetic-grappler",
    name: "Electro-Magnetic Grappler",
    price: 8500,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Latches onto metallic surfaces for maneuvering and scaling walls.",
  },
  {
    id: "nano-spider-tires",
    name: "Nano-Spider Tires",
    price: 9000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Adjusts tread patterns for optimized grip on different terrains.",
  },
  {
    id: "energy-shield-generator",
    name: "Energy Shield Generator",
    price: 10000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Projects a protective force field around the car.",
  },
  {
    id: "kinetic-thrusters",
    name: "Kinetic Thrusters",
    price: 10000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Enables lateral strafing and brief hovering for evasive actions.",
  },
  {
    id: "oil-slick",
    name: "Oil Slick",
    price: 10000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Releases a slick of oil from the car's rear, causing loss of control for pursuing vehicles.",
  },
  {
    id: "molecular-disruptor-mines",
    name: "Molecular Disruptor Mines",
    price: 11000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Deploys destabilizing mines to impair handling of other vehicles.",
  },
  {
    id: "auto-targeting-turret",
    name: "Auto-Targeting Turret",
    price: 12000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Mounts an auto-targeting turret for offensive capabilities.",
  },
  {
    id: "sonic-disruptor",
    name: "Sonic Disruptor",
    price: 12000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Emits powerful sound waves to disorient enemies during combat.",
  },
  {
    id: "adaptive-camouflage-paint",
    name: "Adaptive Camouflage Paint",
    price: 14000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Provides adaptive camouflage to blend with surroundings.",
  },
  {
    id: "neural-interface",
    name: "Neural Interface",
    price: 15000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Connects the car's systems directly to the driver's brain.",
  },
  {
    id: "flame-thrower",
    name: "Flame Thrower",
    price: 15000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Equips the car with a mounted flamethrower for offensive use. (Scorching Ray 2/day)",
  },
  {
    id: "energy-absorption-matrix",
    name: "Energy Absorption Matrix",
    price: 18000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Absorbs and redirects energy-based attacks for defense.",
  },
  {
    id: "cloaking-device",
    name: "Cloaking Device",
    price: 20000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description: "Renders the car temporarily invisible. (Invisibility 1/day)",
  },
  {
    id: "rocket-launcher",
    name: "Rocket Launcher",
    price: 20000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Concealed rocket launcher with guided rockets. (Fireball 1/day)",
  },
  {
    id: "whistle",
    name: "Whistle",
    price: 8000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "An application that calls the car to your location via ping signal if transport is possible.",
  },
  {
    id: "vulcan-cannon-turret",
    name: "Vulcan Cannon Turret",
    price: 45000,
    category: "automotive",
    consumable: false,
    legality: "Regulated",
    type: "Automotive Upgrade",
    description:
      "Military-grade anti-automobile rifle mounted on a retractable swivel deck.",
  },

  // ======================== VEHICLES ========================

  {
    id: "motorbike",
    name: "Motorbike",
    price: 14000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Small",
    capacity: 1,
  },
  {
    id: "motorcycle",
    name: "Motorcycle",
    price: 25000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Small",
    capacity: 2,
  },
  {
    id: "three-wheeler",
    name: "Three-wheeler",
    price: 20000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Small",
    capacity: 2,
  },
  {
    id: "roadster",
    name: "Roadster",
    price: 55000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Medium",
    capacity: 2,
  },
  {
    id: "coupe",
    name: "Coupe",
    price: 40000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Medium",
    capacity: 4,
  },
  {
    id: "sedan",
    name: "Sedan",
    price: 35000,
    category: "vehicles",
    consumable: false,
    legality: "Open",
    type: "Vehicle",
    vehicleSize: "Medium",
    capacity: 5,
  },
];

// Category labels for filter buttons
const shopCategories = {
  all: "ALL ITEMS",
  drugs: "DRUGS",
  medical: "MEDICAL",
  technology: "TECH",
  equipment: "EQUIPMENT",
  gear: "GEAR",
  cyberware: "CYBERWARE",
  robotics: "ROBOTICS",
  optics: "OPTICS",
  weapons: "WEAPONS",
  "weapon-mods": "WEAPON MODS",
  automotive: "AUTOMOTIVE",
  vehicles: "VEHICLES",
};
